[package]
name = "rusty-metro"
version = "0.1.0"
edition = "2024"

[dependencies]
ggez = "0.9.3"
lazy_static = "1.5.0"
lerp = "0.5.0"
rand = "0.9.1"
rand_distr = "0.5.1"
strum = "0.27.1"
strum_macros = "0.27.1"
